
/* إدارة المقاولات المتكاملة — 1075 */
(function(){
'use strict';
const AKEYS=['suppliers','rfqs','purchaseOrders','subcontractors','subcontracts','claims','changeOrders','cashflow','bankRecons','dues','periods','periodEvents','users','budgets'];
const D=()=>window.opsData||(window.opsData={});
const arr=k=>Array.isArray(D()[k])?D()[k]:(D()[k]=[]);
const num=v=>{const n=Number(v||0);return Number.isFinite(n)?n:0;};
const today=()=>new Date().toISOString().slice(0,10);
const money=v=>fmtI(num(v))+' ر.س';
const pName=id=>{const p=(projs||[]).find(x=>x.id===id);return p?p.name:'—';};
const sName=id=>{const x=arr('suppliers').find(x=>x.id===id);return x?x.name:'—';};
const subName=id=>{const x=arr('subcontractors').find(x=>x.id===id);return x?x.name:'—';};
const diffDays=d=>{if(!d)return 0;return Math.floor((new Date(today())-new Date(d))/(86400000));};
const dueBalance=x=>Math.max(0,num(x.total||x.amount)-num(x.paid));
window._opsView='overview';window._opsEdit=null;window._opsProject='';

window.opsMergeData=function(local,cloud){
  const out=Object.assign({},local||{});const c=cloud||{};
  AKEYS.forEach(k=>{const map={};(Array.isArray(c[k])?c[k]:[]).forEach(x=>{if(x&&x.id)map[x.id]=x;});(Array.isArray((local||{})[k])?(local||{})[k]:[]).forEach(x=>{if(x&&x.id)map[x.id]=x;});out[k]=Object.values(map);});
  out.zatca=Object.assign({},c.zatca||{},(local||{}).zatca||{});return out;
};
window.svOps=async function(show){
  try{await _svRetry(window.SOPS,JSON.stringify(D()));if(typeof cloudPushDebounced==='function')cloudPushDebounced();if(show)toast('✅ تم حفظ بيانات إدارة المقاولات','ok');return {ok:true};}catch(e){if(show)toast('فشل حفظ بيانات إدارة المقاولات','er');return {ok:false,err:e};}
};
window.hdIsPeriodClosed=function(date){if(!date)return false;const ym=String(date).slice(0,7);return arr('periods').some(p=>p.month===ym&&p.status==='closed');};
function auditOps(action,detail){try{logEvent(action,detail||'');}catch(e){}}
function projectOpts(sel){return '<option value="">— اختر المشروع —</option>'+projs.map(p=>'<option value="'+esc(p.id)+'" '+(p.id===sel?'selected':'')+'>'+esc(p.name)+'</option>').join('');}
function supplierOpts(sel){return '<option value="">— اختر المورد —</option>'+arr('suppliers').filter(x=>x.active!==false).map(x=>'<option value="'+esc(x.id)+'" '+(x.id===sel?'selected':'')+'>'+esc(x.name)+'</option>').join('');}
function subOpts(sel){return '<option value="">— اختر مقاول الباطن —</option>'+arr('subcontractors').filter(x=>x.active!==false).map(x=>'<option value="'+esc(x.id)+'" '+(x.id===sel?'selected':'')+'>'+esc(x.name)+'</option>').join('');}
function stat(s){const map={draft:['مسودة',''],sent:['مرسل','b'],quoted:['تم الاستلام','b'],approved:['معتمد','g'],active:['نشط','g'],partial:['جزئي','a'],paid:['مدفوع','g'],received:['مستلم','g'],closed:['مغلق','g'],cancelled:['ملغى','r'],rejected:['مرفوض','r'],pending:['بانتظار','a'],submitted:['مقدم','b'],open:['مفتوح','b'],hold:['معلق','a']};const m=map[s]||[s||'—',''];return '<span class="ops-badge '+m[1]+'">'+esc(m[0])+'</span>';}
function btns(type,id){return '<button class="ops-edit" onclick="opsOpen(\''+type+'\',\''+id+'\')">تعديل</button> <button class="ops-danger" onclick="opsDel(\''+type+'\',\''+id+'\')">حذف</button>';}
function empty(t){return '<div class="ops-empty">'+esc(t||'لا توجد بيانات حتى الآن')+'</div>';}
function kpis(items){return '<div class="ops-kpis">'+items.map(x=>'<div class="ops-kpi '+(x.c||'')+'"><div class="l">'+x.l+'</div><div class="v">'+x.v+'</div></div>').join('')+'</div>';}
function card(title,body,action){return '<div class="ops-card"><div class="ops-card-head"><h3>'+title+'</h3>'+(action||'')+'</div>'+body+'</div>';}
function table(headers,rows){if(!rows.length)return empty();return '<div class="ops-table-wrap"><table class="ops-table"><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';}
function record(type,id){const map={supplier:'suppliers',rfq:'rfqs',po:'purchaseOrders',subcontractor:'subcontractors',subcontract:'subcontracts',claim:'claims',change:'changeOrders',cash:'cashflow',bank:'bankRecons',due:'dues',user:'users',budget:'budgets'};return arr(map[type]||type).find(x=>x.id===id);}

window.renderOps=function(){
  const b=document.getElementById('ops-body');if(!b)return;
  document.querySelectorAll('#ops-nav button').forEach(x=>x.classList.toggle('on',x.dataset.ov===window._opsView));
  if(window.HD_ROLE==='accountant'&&['users'].includes(window._opsView))window._opsView='aging';
  const fn={overview:renderOverview,claims:renderClaims,changes:renderChanges,procurement:renderProcurement,suppliers:renderSuppliers,subs:renderSubs,cashflow:renderCashflow,aging:renderAging,bank:renderBank,period:renderPeriod,users:renderUsers,zatca:renderZatca}[window._opsView]||renderOverview;
  b.innerHTML=fn();
};
window.opsGo=function(v){if(window.HD_ROLE==='accountant'&&v==='users')v='aging';window._opsView=v;renderOps();window.scrollTo({top:0,behavior:'smooth'});};

function approvedChanges(pid){return arr('changeOrders').filter(x=>x.projectId===pid&&x.status==='approved').reduce((s,x)=>s+num(x.amount),0);}
function poOpen(pid){return arr('purchaseOrders').filter(x=>(!pid||x.projectId===pid)&&!['cancelled','paid'].includes(x.status)).reduce((s,x)=>s+dueBalance(x),0);}
function subCommitted(pid){const cs=arr('subcontracts').filter(x=>(!pid||x.projectId===pid)&&x.status!=='cancelled');return cs.reduce((s,c)=>{const paid=arr('claims').filter(q=>q.partyType==='subcontractor'&&q.subcontractId===c.id).reduce((a,q)=>a+num(q.paid),0);return s+Math.max(0,num(c.value)-paid);},0);}
function clientClaimOut(pid){return arr('claims').filter(x=>x.partyType==='client'&&(!pid||x.projectId===pid)&&x.status!=='cancelled').reduce((s,x)=>s+dueBalance(x),0);}
function budgetOf(pid){return arr('budgets').find(x=>x.projectId===pid)||null;}
function commandStats(pid){const p=projs.find(x=>x.id===pid);if(!p)return null;const pl=projPL(pid);const ch=approvedChanges(pid);const effective=num(p.contractValue)+ch;const po=poOpen(pid),sub=subCommitted(pid),forecastCost=pl.cost+po+sub;const b=budgetOf(pid);return {p,pl,ch,effective,po,sub,forecastCost,forecastProfit:effective-forecastCost,budget:b?num(b.total):0,claimOut:clientClaimOut(pid)};}
function opsAlerts(pid){const out=[];const ps=pid?projs.filter(p=>p.id===pid):projs.filter(p=>p.status==='active');ps.forEach(p=>{const s=commandStats(p.id);if(!s)return;if(!budgetOf(p.id))out.push({t:'warn',m:'لا توجد ميزانية معتمدة لمشروع «'+p.name+'».'});if(s.effective>0&&s.forecastProfit/s.effective<.1)out.push({t:'bad',m:'هامش الربح المتوقع منخفض في «'+p.name+'» ('+(s.forecastProfit/s.effective*100).toFixed(1)+'%).'});});
  arr('claims').forEach(c=>{if(pid&&c.projectId!==pid)return;if(c.status!=='paid'&&c.status!=='cancelled'&&c.dueDate&&new Date(c.dueDate)<new Date(today())&&dueBalance(c)>0)out.push({t:'bad',m:'مستخلص متأخر '+(c.number||'')+' — '+money(dueBalance(c))});});
  const unre=arr('bankRecons').filter(x=>Math.abs(num(x.bankAmount)-num(x.bookAmount))>.009);if(unre.length)out.push({t:'warn',m:unre.length+' حركة بنكية غير مسواة.'});
  const pend=arr('changeOrders').filter(x=>(!pid||x.projectId===pid)&&x.status==='pending'&&diffDays(x.date)>30);if(pend.length)out.push({t:'warn',m:pend.length+' أمر تغيير بانتظار الاعتماد لأكثر من 30 يومًا.'});
  if((D().zatca||{}).certificateStatus!=='ready')out.push({t:'info',m:'تكامل الفوترة الإلكترونية للمرحلة الثانية غير مربوط بعد.'});return out.slice(0,8);
}
function renderOverview(){
  if(!window._opsProject||!projs.some(p=>p.id===window._opsProject))window._opsProject=(projs.find(p=>p.status==='active')||projs[0]||{}).id||'';
  const pid=window._opsProject;const s=pid?commandStats(pid):null;let h='<select class="ops-project-select" onchange="window._opsProject=this.value;renderOps()">'+projectOpts(pid)+'</select>';
  if(!s)return h+empty('أضف مشروعًا أولاً لعرض مركز المشروع.');
  const margin=s.effective?100*s.forecastProfit/s.effective:0;h+=kpis([{l:'قيمة العقد بعد التغييرات',v:money(s.effective),c:'blue'},{l:'التكلفة الفعلية',v:money(s.pl.cost)},{l:'التزامات مفتوحة',v:money(s.po+s.sub),c:'warn'},{l:'الربح المتوقع',v:money(s.forecastProfit),c:s.forecastProfit>=0?'good':'bad'},{l:'هامش متوقع',v:margin.toFixed(1)+'%',c:margin>=15?'good':margin>=0?'warn':'bad'}]);
  const budget=s.budget||0;const use=budget?Math.min(100,(s.pl.cost/budget)*100):0;
  h+='<div class="ops-grid2">';
  h+=card('🎯 مركز قيادة المشروع','<div class="ops-flow"><div class="step"><b>'+fmtI(s.p.contractValue||0)+'</b>العقد</div><div class="step"><b>'+fmtI(s.budget)+'</b>الميزانية</div><div class="step"><b>'+arr('purchaseOrders').filter(x=>x.projectId===pid).length+'</b>أوامر شراء</div><div class="step"><b>'+arr('subcontracts').filter(x=>x.projectId===pid).length+'</b>عقود باطن</div><div class="step"><b>'+arr('claims').filter(x=>x.projectId===pid).length+'</b>مستخلصات</div><div class="step"><b>'+fmtI(s.pl.cost)+'</b>تكلفة فعلية</div><div class="step"><b>'+fmtI(s.pl.paid)+'</b>تحصيل</div><div class="step"><b>'+fmtI(s.forecastProfit)+'</b>ربح متوقع</div></div><div style="margin-top:12px;font-size:11px;color:#64748b">استهلاك الميزانية</div><div class="ops-progress" style="margin-top:5px"><i style="width:'+use+'%"></i></div><div style="display:flex;justify-content:space-between;font-size:10px;color:#64748b;margin-top:4px"><span>'+use.toFixed(1)+'%</span><span>'+(budget?money(budget):'لم تُحدد الميزانية')+'</span></div>', '<button class="ops-add" onclick="opsOpen(\'budget\',\''+(budgetOf(pid)?.id||'')+'\',\''+pid+'\')">✎ الميزانية</button>');
  const alerts=opsAlerts(pid);h+=card('🧠 مساعد المدير التنفيذي',alerts.length?alerts.map(a=>'<div class="ops-alert '+(a.t==='info'?'info':a.t==='bad'?'':'')+'">'+(a.t==='bad'?'🔴':a.t==='warn'?'🟠':'🔵')+'<div>'+esc(a.m)+'</div></div>').join(''):'<div class="ops-alert ok">✅ لا توجد تنبيهات تشغيلية حرجة للمشروع.</div>');
  h+='</div>';
  const cf=opsForecast(90,pid);h+=kpis([{l:'مستخلصات غير محصلة',v:money(s.claimOut),c:'warn'},{l:'أوامر تغيير معتمدة',v:money(s.ch),c:'blue'},{l:'تدفق 30 يوم',v:money(opsForecast(30,pid).net),c:opsForecast(30,pid).net>=0?'good':'bad'},{l:'تدفق 60 يوم',v:money(opsForecast(60,pid).net),c:opsForecast(60,pid).net>=0?'good':'bad'},{l:'تدفق 90 يوم',v:money(cf.net),c:cf.net>=0?'good':'bad'}]);return h;
}

function renderClaims(){const list=arr('claims').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));const out=list.reduce((s,x)=>s+dueBalance(x),0),paid=list.reduce((s,x)=>s+num(x.paid),0),over=list.filter(x=>x.dueDate&&new Date(x.dueDate)<new Date(today())&&dueBalance(x)>0).reduce((s,x)=>s+dueBalance(x),0);let h=kpis([{l:'إجمالي المستخلصات',v:money(list.reduce((s,x)=>s+num(x.total),0)),c:'blue'},{l:'المدفوع/المحصّل',v:money(paid),c:'good'},{l:'الرصيد',v:money(out),c:'warn'},{l:'متأخر',v:money(over),c:over?'bad':'good'},{l:'عدد المستخلصات',v:list.length}]);const rows=list.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+esc(x.partyType==='subcontractor'?'مقاول باطن':'عميل')+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+money(x.total)+'</td><td>'+money(dueBalance(x))+'</td><td>'+fmtD(x.dueDate)+'</td><td>'+stat(x.status)+'</td><td>'+btns('claim',x.id)+'</td></tr>');return h+card('المستخلصات',table(['الرقم','الجهة','المشروع','الإجمالي','الرصيد','الاستحقاق','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'claim\')">＋ مستخلص</button>');}
function renderChanges(){const l=arr('changeOrders').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));const ap=l.filter(x=>x.status==='approved').reduce((s,x)=>s+num(x.amount),0);let h=kpis([{l:'معتمد',v:money(ap),c:'good'},{l:'بانتظار',v:l.filter(x=>x.status==='pending').length,c:'warn'},{l:'مرفوض',v:l.filter(x=>x.status==='rejected').length,c:'bad'},{l:'أيام تمديد معتمدة',v:l.filter(x=>x.status==='approved').reduce((s,x)=>s+num(x.days),0)+' يوم',c:'blue'},{l:'إجمالي الأوامر',v:l.length}]);const rows=l.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+esc(x.description||'')+'</td><td>'+money(x.amount)+'</td><td>'+num(x.days)+' يوم</td><td>'+stat(x.status)+'</td><td>'+btns('change',x.id)+'</td></tr>');return h+card('أوامر التغيير',table(['الرقم','المشروع','الوصف','القيمة','المدة','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'change\')">＋ أمر تغيير</button>');}
function renderProcurement(){const po=arr('purchaseOrders').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));const rf=arr('rfqs').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));let h=kpis([{l:'قيمة أوامر الشراء',v:money(po.reduce((s,x)=>s+num(x.total),0)),c:'blue'},{l:'رصيد مستحق للموردين',v:money(po.reduce((s,x)=>s+dueBalance(x),0)),c:'warn'},{l:'أوامر معتمدة',v:po.filter(x=>x.status==='approved'||x.status==='received').length,c:'good'},{l:'طلبات تسعير مفتوحة',v:rf.filter(x=>!['closed','cancelled'].includes(x.status)).length},{l:'الموردون النشطون',v:arr('suppliers').filter(x=>x.active!==false).length}]);const por=po.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+esc(sName(x.supplierId))+'</td><td>'+money(x.total)+'</td><td>'+money(dueBalance(x))+'</td><td>'+stat(x.status)+'</td><td>'+btns('po',x.id)+'</td></tr>');const rfr=rf.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+esc(x.title||'')+'</td><td>'+fmtD(x.bidDue)+'</td><td>'+stat(x.status)+'</td><td>'+btns('rfq',x.id)+'</td></tr>');h+='<div class="ops-grid2">'+card('🛒 أوامر الشراء',table(['الرقم','المشروع','المورد','الإجمالي','الرصيد','الحالة',''],por),'<button class="ops-add" onclick="opsOpen(\'po\')">＋ أمر شراء</button>')+card('📨 طلبات التسعير',table(['الرقم','المشروع','العنوان','آخر موعد','الحالة',''],rfr),'<button class="ops-add" onclick="opsOpen(\'rfq\')">＋ طلب تسعير</button>')+'</div>';return h;}
function renderSuppliers(){const l=arr('suppliers').slice().sort((a,b)=>String(a.name).localeCompare(String(b.name),'ar'));const rows=l.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.vat||'—')+'</td><td>'+esc(x.phone||'—')+'</td><td>'+esc(x.category||'—')+'</td><td>'+stat(x.active===false?'hold':'active')+'</td><td>'+btns('supplier',x.id)+'</td></tr>');return kpis([{l:'إجمالي الموردين',v:l.length,c:'blue'},{l:'نشط',v:l.filter(x=>x.active!==false).length,c:'good'},{l:'موقوف',v:l.filter(x=>x.active===false).length,c:'warn'},{l:'أوامر شراء مرتبطة',v:arr('purchaseOrders').filter(x=>x.supplierId).length},{l:'طلبات تسعير',v:arr('rfqs').length}])+card('سجل الموردين',table(['المورد','الرقم الضريبي','الجوال','التصنيف','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'supplier\')">＋ مورد</button>');}
function renderSubs(){const subs=arr('subcontractors');const cons=arr('subcontracts');const sr=subs.map(x=>'<tr><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.specialty||'—')+'</td><td>'+esc(x.vat||'—')+'</td><td>'+esc(x.phone||'—')+'</td><td>'+stat(x.active===false?'hold':'active')+'</td><td>'+btns('subcontractor',x.id)+'</td></tr>');const cr=cons.map(x=>'<tr><td>'+esc(x.number||'—')+'</td><td>'+esc(subName(x.subcontractorId))+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+money(x.value)+'</td><td>'+num(x.retentionPct)+'%</td><td>'+stat(x.status)+'</td><td>'+btns('subcontract',x.id)+'</td></tr>');return kpis([{l:'مقاولو الباطن',v:subs.length,c:'blue'},{l:'قيمة عقود الباطن',v:money(cons.reduce((s,x)=>s+num(x.value),0))},{l:'التزام متبقٍ',v:money(subCommitted('')),c:'warn'},{l:'مستخلصات الباطن',v:arr('claims').filter(x=>x.partyType==='subcontractor').length},{l:'عقود نشطة',v:cons.filter(x=>x.status==='active').length,c:'good'}])+'<div class="ops-grid2">'+card('مقاولو الباطن',table(['الاسم','التخصص','الرقم الضريبي','الجوال','الحالة',''],sr),'<button class="ops-add" onclick="opsOpen(\'subcontractor\')">＋ مقاول</button>')+card('عقود الباطن',table(['العقد','المقاول','المشروع','القيمة','الاحتجاز','الحالة',''],cr),'<button class="ops-add" onclick="opsOpen(\'subcontract\')">＋ عقد باطن</button>')+'</div>';}
function opsForecast(days,pid){const cut=new Date();cut.setDate(cut.getDate()+days);let inn=0,out=0;const within=d=>{if(!d)return false;return new Date(d)<=cut;};arr('claims').forEach(x=>{if(pid&&x.projectId!==pid)return;if(!within(x.dueDate)||['paid','cancelled'].includes(x.status))return;const b=dueBalance(x);if(x.partyType==='subcontractor')out+=b;else inn+=b;});arr('purchaseOrders').forEach(x=>{if(pid&&x.projectId!==pid)return;if(within(x.dueDate)&&!['paid','cancelled'].includes(x.status))out+=dueBalance(x);});arr('dues').forEach(x=>{if(pid&&x.projectId!==pid)return;if(within(x.dueDate)&&x.status!=='paid'){const b=Math.max(0,num(x.amount)-num(x.paid));if(x.side==='ar')inn+=b;else out+=b;}});arr('cashflow').forEach(x=>{if(pid&&x.projectId!==pid)return;if(within(x.date)&&x.status!=='cancelled'){if(x.direction==='in')inn+=num(x.amount);else out+=num(x.amount);}});return {in:inn,out,net:inn-out};}
function renderCashflow(){const f30=opsForecast(30,''),f60=opsForecast(60,''),f90=opsForecast(90,'');const l=arr('cashflow').slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));const rows=l.map(x=>'<tr><td>'+fmtD(x.date)+'</td><td>'+esc(x.direction==='in'?'داخل':'خارج')+'</td><td>'+esc(pName(x.projectId))+'</td><td>'+esc(x.source||'')+'</td><td>'+money(x.amount)+'</td><td>'+stat(x.status||'pending')+'</td><td>'+btns('cash',x.id)+'</td></tr>');let h=kpis([{l:'صافي 30 يوم',v:money(f30.net),c:f30.net>=0?'good':'bad'},{l:'صافي 60 يوم',v:money(f60.net),c:f60.net>=0?'good':'bad'},{l:'صافي 90 يوم',v:money(f90.net),c:f90.net>=0?'good':'bad'},{l:'داخل 90 يوم',v:money(f90.in),c:'good'},{l:'خارج 90 يوم',v:money(f90.out),c:'warn'}]);h+=card('توقعات التدفق النقدي','<div class="ops-grid3"><div class="ops-card" style="margin:0"><h3>30 يوم</h3><div>داخل: <b>'+money(f30.in)+'</b></div><div>خارج: <b>'+money(f30.out)+'</b></div></div><div class="ops-card" style="margin:0"><h3>60 يوم</h3><div>داخل: <b>'+money(f60.in)+'</b></div><div>خارج: <b>'+money(f60.out)+'</b></div></div><div class="ops-card" style="margin:0"><h3>90 يوم</h3><div>داخل: <b>'+money(f90.in)+'</b></div><div>خارج: <b>'+money(f90.out)+'</b></div></div></div><div class="ops-note" style="margin-top:10px">يُحسب تلقائيًا من المستخلصات وأوامر الشراء والذمم، ويضاف إليها أي تدفقات تخطيطية تسجلها هنا.</div>');h+=card('تدفقات تخطيطية إضافية',table(['التاريخ','الاتجاه','المشروع','المصدر','المبلغ','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'cash\')">＋ تدفق</button>');return h;}
function agingRows(){const out=[];arr('claims').forEach(x=>{const b=dueBalance(x);if(b<=0||x.status==='cancelled')return;out.push({id:x.id,side:x.partyType==='subcontractor'?'ap':'ar',party:x.partyType==='subcontractor'?subName(x.subcontractorId):(projs.find(p=>p.id===x.projectId)?.client||pName(x.projectId)),projectId:x.projectId,ref:x.number,date:x.date,dueDate:x.dueDate,amount:num(x.total),paid:num(x.paid),balance:b,source:'مستخلص'});});arr('purchaseOrders').forEach(x=>{const b=dueBalance(x);if(b<=0||x.status==='cancelled')return;out.push({id:x.id,side:'ap',party:sName(x.supplierId),projectId:x.projectId,ref:x.number,date:x.date,dueDate:x.dueDate,amount:num(x.total),paid:num(x.paid),balance:b,source:'أمر شراء'});});arr('dues').forEach(x=>{const b=Math.max(0,num(x.amount)-num(x.paid));if(b<=0||x.status==='paid')return;out.push({id:x.id,side:x.side,party:x.party,projectId:x.projectId,ref:x.ref,date:x.date,dueDate:x.dueDate,amount:num(x.amount),paid:num(x.paid),balance:b,source:'ذمة يدوية'});});return out;}
function bucket(r){if(!r.dueDate)return 'current';const d=diffDays(r.dueDate);if(d<=0)return 'current';if(d<=30)return '30';if(d<=60)return '60';if(d<=90)return '90';return '90p';}
function renderAging(){const rows=agingRows();const ar=rows.filter(x=>x.side==='ar'),ap=rows.filter(x=>x.side==='ap');const sum=(a)=>a.reduce((s,x)=>s+x.balance,0);const buckets={current:0,'30':0,'60':0,'90':0,'90p':0};rows.forEach(x=>buckets[bucket(x)]+=x.balance);let h=kpis([{l:'الذمم المدينة',v:money(sum(ar)),c:'good'},{l:'الذمم الدائنة',v:money(sum(ap)),c:'warn'},{l:'صافي الذمم',v:money(sum(ar)-sum(ap)),c:sum(ar)>=sum(ap)?'good':'bad'},{l:'بنود متأخرة',v:rows.filter(x=>bucket(x)!=='current').length,c:'bad'},{l:'إجمالي البنود',v:rows.length}]);h+='<div class="ops-aging-grid">'+[['current','غير مستحق'],['30','1–30 يوم'],['60','31–60 يوم'],['90','61–90 يوم'],['90p','أكثر من 90']].map(([k,l])=>'<div class="ops-aging-box"><b>'+money(buckets[k])+'</b><span>'+l+'</span></div>').join('')+'</div><div style="height:10px"></div>';const rr=rows.sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).map(x=>'<tr><td>'+esc(x.side==='ar'?'مدينة':'دائنة')+'</td><td>'+esc(x.party||'—')+'</td><td>'+esc(x.ref||'—')+'</td><td>'+esc(x.source)+'</td><td>'+fmtD(x.dueDate)+'</td><td>'+money(x.balance)+'</td><td>'+esc(bucket(x)==='current'?'غير مستحق':bucket(x)==='90p'?'>90':bucket(x))+'</td></tr>');h+=card('تفاصيل أعمار الذمم',table(['النوع','الطرف','المرجع','المصدر','الاستحقاق','الرصيد','العمر'],rr),'<button class="ops-add" onclick="opsOpen(\'due\')">＋ ذمة يدوية</button>');const unallocated=projs.filter(p=>p.status!=='study').reduce((s,p)=>s+Math.max(0,projPL(p.id).outstanding),0)-sum(ar);if(unallocated>1)h+='<div class="ops-note">يوجد تقريبًا <b>'+money(unallocated)+'</b> من مستحقات العقود في النظام الأصلي بدون تاريخ استحقاق محدد، لذلك لا تدخل في أعمار الذمم حتى تُسجل كمستخلص أو ذمة بتاريخ استحقاق.</div>';return h;}
function renderBank(){const l=arr('bankRecons').slice().sort((a,b)=>(b.date||'').localeCompare(a.date||''));const diff=l.reduce((s,x)=>s+Math.abs(num(x.bankAmount)-num(x.bookAmount)),0);const un=l.filter(x=>Math.abs(num(x.bankAmount)-num(x.bookAmount))>.009);const rows=l.map(x=>{const d=num(x.bankAmount)-num(x.bookAmount);return '<tr><td>'+fmtD(x.date)+'</td><td>'+esc(x.bankRef||'—')+'</td><td>'+esc(x.description||'')+'</td><td>'+money(x.bookAmount)+'</td><td>'+money(x.bankAmount)+'</td><td style="color:'+(Math.abs(d)<.01?'#15803d':'#b91c1c')+'">'+money(d)+'</td><td>'+stat(Math.abs(d)<.01?'closed':'pending')+'</td><td>'+btns('bank',x.id)+'</td></tr>';});return kpis([{l:'الحركات',v:l.length,c:'blue'},{l:'مسواة',v:l.length-un.length,c:'good'},{l:'غير مسواة',v:un.length,c:un.length?'bad':'good'},{l:'إجمالي الفروقات',v:money(diff),c:diff?'bad':'good'},{l:'آخر حركة',v:l[0]?fmtD(l[0].date):'—'}])+card('التسوية البنكية',table(['التاريخ','مرجع البنك','البيان','الدفاتر','البنك','الفرق','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'bank\')">＋ حركة بنكية</button>');}
function monthLabel(ym){if(!ym)return'';const [y,m]=ym.split('-');const ns=['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];return (ns[+m-1]||m)+' '+y;}
function recentMonths(){const a=[];const d=new Date();for(let i=0;i<12;i++){const x=new Date(d.getFullYear(),d.getMonth()-i,1);a.push(x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0'));}return a;}
function renderPeriod(){const rows=recentMonths().map(ym=>{const p=arr('periods').find(x=>x.month===ym);const closed=p&&p.status==='closed';return '<tr><td><b>'+monthLabel(ym)+'</b></td><td>'+stat(closed?'closed':'open')+'</td><td>'+esc(p?.closedBy||'—')+'</td><td>'+fmtD(p?.closedAt?new Date(p.closedAt).toISOString().slice(0,10):'')+'</td><td>'+(closed?'<button class="ops-edit" onclick="opsTogglePeriod(\''+ym+'\',false)">إعادة فتح</button>':'<button class="ops-danger" onclick="opsTogglePeriod(\''+ym+'\',true)">إقفال</button>')+'</td></tr>';});const j=(journals||[]).slice(0,30).map(x=>'<tr><td>'+fmtD(x.date)+'</td><td>'+esc(x.desc||'')+'</td><td>'+money((x.lines||[]).reduce((s,l)=>s+num(l.debit),0))+'</td><td>'+esc(x.source||'')+'</td><td><button class="ops-edit" onclick="opsReverseJournal(\''+x.id+'\')">عكس القيد</button></td></tr>');return '<div class="ops-note"><b>الإقفال الفعلي:</b> يمنع النظام الآن حفظ فواتير وقيود يومية وسجلات تشغيلية بتاريخ يقع في شهر مقفل. إعادة الفتح تتطلب سببًا ويُسجل في سجل التغيير.</div><div class="ops-grid2">'+card('🔒 الفترات المحاسبية',table(['الفترة','الحالة','أقفل بواسطة','تاريخ الإقفال','الإجراء'],rows))+card('↩️ عكس القيود',table(['التاريخ','البيان','المبلغ','المصدر',''],j))+'</div>';}
window.opsTogglePeriod=async function(ym,close){if(window.HD_ROLE==='accountant'&&close)return toast('هذه الصلاحية للمالك/المدير','er');let p=arr('periods').find(x=>x.month===ym);if(close){const ok=await confirm2({title:'إقفال '+monthLabel(ym),msg:'بعد الإقفال لن يقبل النظام تسجيل فواتير أو قيود أو حركات تشغيلية بهذا التاريخ.',ok:'إقفال الفترة',danger:true});if(!ok)return;if(!p){p={id:uid('per'),month:ym};arr('periods').push(p);}p.status='closed';p.closedAt=Date.now();p.closedBy=window.HD_USER||'المالك';p.updatedAt=Date.now();arr('periodEvents').unshift({id:uid('pev'),month:ym,action:'close',reason:'إقفال الفترة',t:Date.now(),u:window.HD_USER||''});auditOps('إقفال فترة',ym);}else{const reason=prompt('سبب إعادة فتح الفترة:');if(!reason)return;if(p){p.status='open';p.reopenedAt=Date.now();p.reopenReason=reason;p.updatedAt=Date.now();}arr('periodEvents').unshift({id:uid('pev'),month:ym,action:'reopen',reason,t:Date.now(),u:window.HD_USER||''});auditOps('إعادة فتح فترة',ym+' — '+reason);}await svOps(false);renderOps();};
window.opsReverseJournal=async function(id){const j=(journals||[]).find(x=>x.id===id);if(!j)return;const d=prompt('تاريخ قيد العكس (YYYY-MM-DD):',today());if(!d)return;if(hdIsPeriodClosed(d))return toast('الفترة المحددة مقفلة','er');const ok=await confirm2({title:'عكس القيد',msg:'سيُنشأ قيد معاكس لـ <strong>'+esc(j.desc||'')+'</strong> بتاريخ '+esc(d)+'.',ok:'إنشاء قيد العكس',danger:false});if(!ok)return;const lines=(j.lines||[]).map(l=>({acc:l.acc,debit:num(l.credit),credit:num(l.debit)}));journals.unshift({id:uid('jrn'),date:d,desc:'عكس: '+(j.desc||''),source:'reversal',reverses:id,lines,t:Date.now(),u:window.HD_USER||''});svJRN();auditOps('عكس قيد',j.desc||id);toast('✅ تم إنشاء قيد العكس','ok');renderOps();};
function renderUsers(){const l=arr('users');const roleNames={owner:'مالك',manager:'مدير',accountant:'محاسب',project_manager:'مدير مشروع',procurement:'مشتريات',viewer:'مشاهدة'};const rows=l.map(x=>'<tr><td><b>'+esc(x.name||'—')+'</b></td><td>'+esc(x.email||'—')+'</td><td>'+esc(roleNames[x.role]||x.role||'—')+'</td><td>'+stat(x.active===false?'hold':'active')+'</td><td>'+btns('user',x.id)+'</td></tr>');const matrix='<div class="ops-table-wrap"><table class="ops-table"><thead><tr><th>الدور</th><th>المشاريع</th><th>المشتريات</th><th>المالية</th><th>الإقفال</th><th>المستخدمون</th></tr></thead><tbody><tr><td>مالك</td><td>كامل</td><td>كامل</td><td>كامل</td><td>نعم</td><td>نعم</td></tr><tr><td>مدير</td><td>كامل</td><td>اعتماد</td><td>تقارير</td><td>لا</td><td>لا</td></tr><tr><td>محاسب</td><td>قراءة</td><td>قراءة</td><td>كامل</td><td>عرض</td><td>لا</td></tr><tr><td>مدير مشروع</td><td>مشاريعه</td><td>طلب</td><td>ملخص</td><td>لا</td><td>لا</td></tr><tr><td>مشتريات</td><td>قراءة</td><td>كامل</td><td>ذمم مورّدين</td><td>لا</td><td>لا</td></tr><tr><td>مشاهدة</td><td>قراءة</td><td>قراءة</td><td>قراءة</td><td>لا</td><td>لا</td></tr></tbody></table></div>';return '<div class="ops-note">الحساب الحالي: <b>'+esc(window.HD_USER||'—')+'</b>. هذه الشاشة تحفظ هيكل المستخدمين والصلاحيات التشغيلية. إنشاء حساب دخول سحابي جديد يظل مرتبطًا بجدول الحسابات في Supabase ولا يتم إنشاء كلمات مرور من داخل الواجهة.</div>'+card('المستخدمون',table(['الاسم','البريد','الدور','الحالة',''],rows),'<button class="ops-add" onclick="opsOpen(\'user\')">＋ مستخدم</button>')+card('مصفوفة الصلاحيات المقترحة',matrix);}
function zatcaChecks(){const sales=invs.filter(i=>i.type==='revenue'&&i.status!=='cancelled');const unique=new Set(sales.map(i=>i.number)).size===sales.filter(i=>i.number).length;return [{l:'اسم المنشأة',ok:!!(sett.name||'')},{l:'الرقم الضريبي',ok:/^3\d{13}3$/.test(String(sett.vn||'').replace(/\D/g,''))},{l:'أرقام الفواتير فريدة',ok:unique},{l:'تواريخ وقيم الفواتير موجودة',ok:sales.every(i=>i.date&&num(i.total)>0)},{l:'احتساب الضريبة محفوظ',ok:sales.every(i=>num(i.vat)>=0)},{l:'رمز QR الأساسي موجود',ok:typeof zatcaBase64==='function'},{l:'شهادة/CSID للمرحلة الثانية',ok:(D().zatca||{}).certificateStatus==='ready'},{l:'بيئة الربط محددة',ok:(D().zatca||{}).environment!=='none'}];}
function renderZatca(){const z=D().zatca||(D().zatca={});const ck=zatcaChecks(),ok=ck.filter(x=>x.ok).length;let h=kpis([{l:'درجة الجاهزية',v:Math.round(ok/ck.length*100)+'%',c:ok===ck.length?'good':'warn'},{l:'فواتير مبيعات',v:invs.filter(i=>i.type==='revenue').length,c:'blue'},{l:'الرقم الضريبي',v:sett.vn||'غير مدخل',c:sett.vn?'good':'bad'},{l:'الشهادة',v:z.certificateStatus==='ready'?'مجهزة':'غير مربوطة',c:z.certificateStatus==='ready'?'good':'warn'},{l:'البيئة',v:z.environment==='production'?'إنتاج':z.environment==='sandbox'?'اختبار':'غير محددة'}]);h+='<div class="ops-grid2">'+card('فحص الجاهزية',ck.map(x=>'<div class="ops-zcheck"><span class="'+(x.ok?'yes':'no')+'">'+(x.ok?'✓':'✕')+'</span><span>'+esc(x.l)+'</span></div>').join(''))+card('إعداد المرحلة الثانية','<div class="ops-note">النظام الحالي يدعم بيانات الضريبة وQR، لكن <b>الإرسال الفعلي للمرحلة الثانية</b> يحتاج شهادة/CSID وربط رسمي بواجهات هيئة الزكاة والضريبة والجمارك. لا يتم تخزين مفاتيح سرية داخل المستودع العام.</div><div class="ops-form"><div class="ops-f"><label>البيئة</label><select id="ops-z-env"><option value="none" '+(z.environment==='none'?'selected':'')+'>غير محددة</option><option value="sandbox" '+(z.environment==='sandbox'?'selected':'')+'>اختبار</option><option value="production" '+(z.environment==='production'?'selected':'')+'>إنتاج</option></select></div><div class="ops-f"><label>حالة الشهادة/CSID</label><select id="ops-z-cert"><option value="none" '+(z.certificateStatus!=='ready'?'selected':'')+'>غير مربوطة</option><option value="ready" '+(z.certificateStatus==='ready'?'selected':'')+'>مجهزة خارج النظام</option></select></div><div class="ops-f full"><label>ملاحظات</label><textarea id="ops-z-note">'+esc(z.notes||'')+'</textarea></div></div><button class="ops-add" style="margin-top:10px" onclick="opsSaveZatca()">حفظ الإعداد</button>')+'</div>';return h;}
window.opsSaveZatca=async function(){D().zatca={environment:document.getElementById('ops-z-env').value,certificateStatus:document.getElementById('ops-z-cert').value,notes:document.getElementById('ops-z-note').value.trim(),updatedAt:Date.now()};await svOps(false);auditOps('تحديث جاهزية الفوترة الإلكترونية',D().zatca.environment);renderOps();toast('تم حفظ إعداد الجاهزية','ok');};

window.renderOpsDashboardStrip=function(){const w=document.getElementById('ops-db-strip');if(!w)return;const alerts=opsAlerts('');const cf=opsForecast(30,'');const aging=agingRows();w.innerHTML='<div class="ops-db-strip"><div class="ops-db-mini" onclick="goTab(\'ops\');opsGo(\'overview\')"><b>'+alerts.length+'</b><span>تنبيهات إدارة المقاولات</span></div><div class="ops-db-mini" onclick="goTab(\'ops\');opsGo(\'aging\')"><b>'+money(aging.filter(x=>x.side==='ar').reduce((s,x)=>s+x.balance,0))+'</b><span>ذمم مدينة مجدولة</span></div><div class="ops-db-mini" onclick="goTab(\'ops\');opsGo(\'procurement\')"><b>'+money(poOpen(''))+'</b><span>التزامات أوامر شراء</span></div><div class="ops-db-mini" onclick="goTab(\'ops\');opsGo(\'cashflow\')"><b style="color:'+(cf.net>=0?'#15803d':'#b91c1c')+'">'+money(cf.net)+'</b><span>صافي تدفق 30 يوم</span></div></div>';};

function field(id,l,type='text',val='',extra=''){return '<div class="ops-f"><label>'+l+'</label><input id="'+id+'" type="'+type+'" value="'+esc(val)+'" '+extra+'></div>';}
function selectf(id,l,opts,full){return '<div class="ops-f '+(full?'full':'')+'"><label>'+l+'</label><select id="'+id+'">'+opts+'</select></div>';}
function textf(id,l,val){return '<div class="ops-f full"><label>'+l+'</label><textarea id="'+id+'">'+esc(val||'')+'</textarea></div>';}
window.opsOpen=function(type,id,preset){window._opsEdit={type,id:id||'',preset:preset||''};const x=id?record(type,id):{};let title='إضافة',f='';
 if(type==='supplier'){title=id?'تعديل مورد':'مورد جديد';f=field('of-name','اسم المورد','text',x.name)+field('of-vat','الرقم الضريبي','text',x.vat)+field('of-phone','الجوال','text',x.phone)+field('of-email','البريد','email',x.email)+field('of-cat','التصنيف','text',x.category)+selectf('of-active','الحالة','<option value="1" '+(x.active!==false?'selected':'')+'>نشط</option><option value="0" '+(x.active===false?'selected':'')+'>موقوف</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='rfq'){title=id?'تعديل طلب تسعير':'طلب تسعير جديد';f=field('of-no','رقم الطلب','text',x.number||('RFQ-'+String(arr('rfqs').length+1).padStart(3,'0')))+field('of-date','التاريخ','date',x.date||today())+selectf('of-proj','المشروع',projectOpts(x.projectId))+field('of-title','العنوان','text',x.title)+field('of-due','آخر موعد للعروض','date',x.bidDue)+selectf('of-status','الحالة','<option value="draft" '+(x.status==='draft'?'selected':'')+'>مسودة</option><option value="sent" '+(x.status==='sent'?'selected':'')+'>مرسل</option><option value="quoted" '+(x.status==='quoted'?'selected':'')+'>استلمت عروض</option><option value="closed" '+(x.status==='closed'?'selected':'')+'>مغلق</option>')+textf('of-sups','الموردون المدعوون (أسماء أو ملاحظات)',x.suppliersText)+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='po'){title=id?'تعديل أمر شراء':'أمر شراء جديد';f=field('of-no','رقم أمر الشراء','text',x.number||('PO-'+String(arr('purchaseOrders').length+1).padStart(4,'0')))+field('of-date','التاريخ','date',x.date||today())+selectf('of-proj','المشروع',projectOpts(x.projectId))+selectf('of-supplier','المورد',supplierOpts(x.supplierId))+field('of-amount','القيمة قبل الضريبة','number',x.amount,'step="0.01"')+field('of-vrate','نسبة الضريبة %','number',x.vatRate==null?15:x.vatRate,'step="0.01"')+field('of-paid','المدفوع','number',x.paid||0,'step="0.01"')+field('of-due','تاريخ الاستحقاق','date',x.dueDate)+selectf('of-status','الحالة','<option value="draft" '+(x.status==='draft'?'selected':'')+'>مسودة</option><option value="approved" '+(x.status==='approved'?'selected':'')+'>معتمد</option><option value="received" '+(x.status==='received'?'selected':'')+'>مستلم</option><option value="partial" '+(x.status==='partial'?'selected':'')+'>دفع جزئي</option><option value="paid" '+(x.status==='paid'?'selected':'')+'>مدفوع</option><option value="cancelled" '+(x.status==='cancelled'?'selected':'')+'>ملغى</option>')+textf('of-notes','وصف/ملاحظات',x.notes);}
 else if(type==='subcontractor'){title=id?'تعديل مقاول باطن':'مقاول باطن جديد';f=field('of-name','الاسم','text',x.name)+field('of-spec','التخصص','text',x.specialty)+field('of-vat','الرقم الضريبي','text',x.vat)+field('of-phone','الجوال','text',x.phone)+field('of-email','البريد','email',x.email)+selectf('of-active','الحالة','<option value="1" '+(x.active!==false?'selected':'')+'>نشط</option><option value="0" '+(x.active===false?'selected':'')+'>موقوف</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='subcontract'){title=id?'تعديل عقد باطن':'عقد باطن جديد';f=field('of-no','رقم العقد','text',x.number||('SC-'+String(arr('subcontracts').length+1).padStart(3,'0')))+selectf('of-proj','المشروع',projectOpts(x.projectId))+selectf('of-sub','مقاول الباطن',subOpts(x.subcontractorId))+field('of-value','قيمة العقد','number',x.value,'step="0.01"')+field('of-ret','نسبة الاحتجاز %','number',x.retentionPct||0,'step="0.01"')+field('of-start','تاريخ البداية','date',x.startDate||today())+field('of-end','تاريخ النهاية','date',x.endDate)+selectf('of-status','الحالة','<option value="active" '+(x.status==='active'?'selected':'')+'>نشط</option><option value="closed" '+(x.status==='closed'?'selected':'')+'>مغلق</option><option value="hold" '+(x.status==='hold'?'selected':'')+'>معلق</option><option value="cancelled" '+(x.status==='cancelled'?'selected':'')+'>ملغى</option>')+textf('of-notes','نطاق العمل/ملاحظات',x.notes);}
 else if(type==='claim'){title=id?'تعديل مستخلص':'مستخلص جديد';f=field('of-no','رقم المستخلص','text',x.number||('CL-'+String(arr('claims').length+1).padStart(4,'0')))+field('of-date','التاريخ','date',x.date||today())+selectf('of-party','جهة المستخلص','<option value="client" '+(x.partyType!=='subcontractor'?'selected':'')+'>عميل — ذمة مدينة</option><option value="subcontractor" '+(x.partyType==='subcontractor'?'selected':'')+'>مقاول باطن — ذمة دائنة</option>')+selectf('of-proj','المشروع',projectOpts(x.projectId))+selectf('of-sub','مقاول الباطن (عند الحاجة)',subOpts(x.subcontractorId))+selectf('of-subcontract','عقد الباطن (اختياري)','<option value="">—</option>'+arr('subcontracts').map(c=>'<option value="'+esc(c.id)+'" '+(c.id===x.subcontractId?'selected':'')+'>'+esc(c.number+' — '+subName(c.subcontractorId))+'</option>').join(''))+field('of-gross','قيمة الأعمال','number',x.gross,'step="0.01"')+field('of-ret','الاحتجاز %','number',x.retentionPct||0,'step="0.01"')+field('of-vrate','الضريبة %','number',x.vatRate==null?15:x.vatRate,'step="0.01"')+field('of-paid','المحصّل/المدفوع','number',x.paid||0,'step="0.01"')+field('of-due','تاريخ الاستحقاق','date',x.dueDate)+selectf('of-status','الحالة','<option value="submitted" '+(x.status==='submitted'?'selected':'')+'>مقدم</option><option value="approved" '+(x.status==='approved'?'selected':'')+'>معتمد</option><option value="partial" '+(x.status==='partial'?'selected':'')+'>جزئي</option><option value="paid" '+(x.status==='paid'?'selected':'')+'>مسدد</option><option value="rejected" '+(x.status==='rejected'?'selected':'')+'>مرفوض</option><option value="cancelled" '+(x.status==='cancelled'?'selected':'')+'>ملغى</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='change'){title=id?'تعديل أمر تغيير':'أمر تغيير جديد';f=field('of-no','رقم أمر التغيير','text',x.number||('CO-'+String(arr('changeOrders').length+1).padStart(3,'0')))+field('of-date','التاريخ','date',x.date||today())+selectf('of-proj','المشروع',projectOpts(x.projectId))+field('of-amount','القيمة (+/-)','number',x.amount,'step="0.01"')+field('of-days','أيام التمديد','number',x.days||0)+selectf('of-status','الحالة','<option value="pending" '+(x.status==='pending'?'selected':'')+'>بانتظار الاعتماد</option><option value="approved" '+(x.status==='approved'?'selected':'')+'>معتمد</option><option value="rejected" '+(x.status==='rejected'?'selected':'')+'>مرفوض</option><option value="cancelled" '+(x.status==='cancelled'?'selected':'')+'>ملغى</option>')+textf('of-desc','وصف التغيير',x.description)+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='cash'){title=id?'تعديل تدفق':'تدفق تخطيطي';f=field('of-date','التاريخ المتوقع','date',x.date||today())+selectf('of-dir','الاتجاه','<option value="in" '+(x.direction!=='out'?'selected':'')+'>داخل</option><option value="out" '+(x.direction==='out'?'selected':'')+'>خارج</option>')+selectf('of-proj','المشروع',projectOpts(x.projectId))+field('of-source','المصدر/الغرض','text',x.source)+field('of-amount','المبلغ','number',x.amount,'step="0.01"')+selectf('of-status','الحالة','<option value="pending" '+(x.status!=='closed'?'selected':'')+'>متوقع</option><option value="closed" '+(x.status==='closed'?'selected':'')+'>تم</option><option value="cancelled" '+(x.status==='cancelled'?'selected':'')+'>ملغى</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='bank'){title=id?'تعديل حركة بنكية':'حركة تسوية بنكية';f=field('of-date','التاريخ','date',x.date||today())+field('of-ref','مرجع البنك','text',x.bankRef)+selectf('of-proj','المشروع (اختياري)',projectOpts(x.projectId))+field('of-book','مبلغ الدفاتر','number',x.bookAmount,'step="0.01"')+field('of-bank','مبلغ كشف البنك','number',x.bankAmount,'step="0.01"')+textf('of-desc','البيان',x.description)+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='due'){title=id?'تعديل ذمة':'ذمة يدوية';f=selectf('of-side','النوع','<option value="ar" '+(x.side!=='ap'?'selected':'')+'>مدينة — لنا</option><option value="ap" '+(x.side==='ap'?'selected':'')+'>دائنة — علينا</option>')+field('of-party','الطرف','text',x.party)+field('of-ref','المرجع','text',x.ref)+selectf('of-proj','المشروع',projectOpts(x.projectId))+field('of-date','التاريخ','date',x.date||today())+field('of-due','الاستحقاق','date',x.dueDate)+field('of-amount','المبلغ','number',x.amount,'step="0.01"')+field('of-paid','المسدد','number',x.paid||0,'step="0.01"')+selectf('of-status','الحالة','<option value="open" '+(x.status!=='paid'?'selected':'')+'>مفتوح</option><option value="paid" '+(x.status==='paid'?'selected':'')+'>مسدد</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='user'){title=id?'تعديل مستخدم':'مستخدم جديد';f=field('of-name','الاسم','text',x.name)+field('of-email','البريد','email',x.email)+selectf('of-role','الدور','<option value="owner" '+(x.role==='owner'?'selected':'')+'>مالك</option><option value="manager" '+(x.role==='manager'?'selected':'')+'>مدير</option><option value="accountant" '+(x.role==='accountant'?'selected':'')+'>محاسب</option><option value="project_manager" '+(x.role==='project_manager'?'selected':'')+'>مدير مشروع</option><option value="procurement" '+(x.role==='procurement'?'selected':'')+'>مشتريات</option><option value="viewer" '+(x.role==='viewer'?'selected':'')+'>مشاهدة</option>')+selectf('of-active','الحالة','<option value="1" '+(x.active!==false?'selected':'')+'>نشط</option><option value="0" '+(x.active===false?'selected':'')+'>موقوف</option>')+textf('of-notes','ملاحظات',x.notes);}
 else if(type==='budget'){const pid=preset||x.projectId||window._opsProject;title=x.id?'تعديل ميزانية المشروع':'ميزانية المشروع';f='<input type="hidden" id="of-proj" value="'+esc(pid)+'">'+field('of-total','الميزانية الإجمالية','number',x.total,'step="0.01"')+field('of-materials','مواد','number',x.materials,'step="0.01"')+field('of-labor','عمالة','number',x.labor,'step="0.01"')+field('of-equipment','معدات','number',x.equipment,'step="0.01"')+field('of-subcontracts','مقاولو باطن','number',x.subcontracts,'step="0.01"')+field('of-overhead','مصاريف عامة/احتياطي','number',x.overhead,'step="0.01"')+textf('of-notes','ملاحظات الميزانية',x.notes);}
 else return;
 document.getElementById('ops-modal-title').textContent=title;document.getElementById('ops-modal-body').innerHTML='<div class="ops-form">'+f+'</div>';document.getElementById('ops-modal').classList.add('show');};
window.opsCloseModal=function(){document.getElementById('ops-modal').classList.remove('show');window._opsEdit=null;};
function v(id){const e=document.getElementById(id);return e?e.value:'';}function n(id){return num(v(id));}
window.opsSaveForm=async function(){const e=window._opsEdit;if(!e)return;const type=e.type,old=e.id?record(type,e.id):null;let x=old?Object.assign({},old):{id:uid('ops'),createdAt:Date.now()};const checkDate=d=>{if(d&&hdIsPeriodClosed(d)){toast('🔒 لا يمكن الحفظ في فترة مقفلة','er');return false;}return true;};
 if(type==='supplier'){if(!v('of-name').trim())return toast('اكتب اسم المورد','er');Object.assign(x,{name:v('of-name').trim(),vat:v('of-vat').trim(),phone:v('of-phone').trim(),email:v('of-email').trim(),category:v('of-cat').trim(),active:v('of-active')==='1',notes:v('of-notes').trim()});}
 else if(type==='rfq'){if(!checkDate(v('of-date')))return;if(!v('of-no').trim())return toast('اكتب رقم الطلب','er');Object.assign(x,{number:v('of-no').trim(),date:v('of-date'),projectId:v('of-proj'),title:v('of-title').trim(),bidDue:v('of-due'),status:v('of-status'),suppliersText:v('of-sups').trim(),notes:v('of-notes').trim()});}
 else if(type==='po'){if(!checkDate(v('of-date')))return;if(!v('of-no').trim()||!v('of-supplier'))return toast('رقم الأمر والمورد مطلوبان','er');const amount=n('of-amount'),vr=n('of-vrate'),vat=amount*vr/100,total=amount+vat;Object.assign(x,{number:v('of-no').trim(),date:v('of-date'),projectId:v('of-proj'),supplierId:v('of-supplier'),amount,vatRate:vr,vat,total,paid:n('of-paid'),dueDate:v('of-due'),status:v('of-status'),notes:v('of-notes').trim()});}
 else if(type==='subcontractor'){if(!v('of-name').trim())return toast('اكتب اسم المقاول','er');Object.assign(x,{name:v('of-name').trim(),specialty:v('of-spec').trim(),vat:v('of-vat').trim(),phone:v('of-phone').trim(),email:v('of-email').trim(),active:v('of-active')==='1',notes:v('of-notes').trim()});}
 else if(type==='subcontract'){if(!checkDate(v('of-start')))return;if(!v('of-proj')||!v('of-sub'))return toast('المشروع والمقاول مطلوبان','er');Object.assign(x,{number:v('of-no').trim(),projectId:v('of-proj'),subcontractorId:v('of-sub'),value:n('of-value'),retentionPct:n('of-ret'),startDate:v('of-start'),endDate:v('of-end'),status:v('of-status'),notes:v('of-notes').trim()});}
 else if(type==='claim'){if(!checkDate(v('of-date')))return;if(!v('of-proj'))return toast('اختر المشروع','er');const gross=n('of-gross'),rp=n('of-ret'),vr=n('of-vrate'),ret=gross*rp/100,base=gross-ret,vat=base*vr/100,total=base+vat;Object.assign(x,{number:v('of-no').trim(),date:v('of-date'),partyType:v('of-party'),projectId:v('of-proj'),subcontractorId:v('of-sub'),subcontractId:v('of-subcontract'),gross,retentionPct:rp,retention:ret,vatRate:vr,vat,total,paid:n('of-paid'),dueDate:v('of-due'),status:v('of-status'),notes:v('of-notes').trim()});}
 else if(type==='change'){if(!checkDate(v('of-date')))return;if(!v('of-proj'))return toast('اختر المشروع','er');Object.assign(x,{number:v('of-no').trim(),date:v('of-date'),projectId:v('of-proj'),amount:n('of-amount'),days:n('of-days'),status:v('of-status'),description:v('of-desc').trim(),notes:v('of-notes').trim()});}
 else if(type==='cash'){if(!checkDate(v('of-date')))return;Object.assign(x,{date:v('of-date'),direction:v('of-dir'),projectId:v('of-proj'),source:v('of-source').trim(),amount:n('of-amount'),status:v('of-status'),notes:v('of-notes').trim()});}
 else if(type==='bank'){if(!checkDate(v('of-date')))return;Object.assign(x,{date:v('of-date'),bankRef:v('of-ref').trim(),projectId:v('of-proj'),bookAmount:n('of-book'),bankAmount:n('of-bank'),description:v('of-desc').trim(),notes:v('of-notes').trim()});}
 else if(type==='due'){if(!checkDate(v('of-date')))return;Object.assign(x,{side:v('of-side'),party:v('of-party').trim(),ref:v('of-ref').trim(),projectId:v('of-proj'),date:v('of-date'),dueDate:v('of-due'),amount:n('of-amount'),paid:n('of-paid'),status:v('of-status'),notes:v('of-notes').trim()});}
 else if(type==='user'){if(!v('of-name').trim())return toast('اكتب الاسم','er');Object.assign(x,{name:v('of-name').trim(),email:v('of-email').trim(),role:v('of-role'),active:v('of-active')==='1',notes:v('of-notes').trim()});}
 else if(type==='budget'){const pid=v('of-proj');if(!pid)return toast('المشروع غير محدد','er');Object.assign(x,{projectId:pid,total:n('of-total'),materials:n('of-materials'),labor:n('of-labor'),equipment:n('of-equipment'),subcontracts:n('of-subcontracts'),overhead:n('of-overhead'),notes:v('of-notes').trim()});}
 const map={supplier:'suppliers',rfq:'rfqs',po:'purchaseOrders',subcontractor:'subcontractors',subcontract:'subcontracts',claim:'claims',change:'changeOrders',cash:'cashflow',bank:'bankRecons',due:'dues',user:'users',budget:'budgets'};const a=arr(map[type]);if(old){const i=a.findIndex(z=>z.id===old.id);if(i>=0)a[i]=Object.assign(x,{updatedAt:Date.now()});}else a.unshift(Object.assign(x,{updatedAt:Date.now()}));await svOps(false);auditOps((old?'تعديل ':'إضافة ')+type,x.number||x.name||x.projectId||'');opsCloseModal();renderOps();renderOpsDashboardStrip();toast('✅ تم الحفظ','ok');};
window.opsDel=async function(type,id){const x=record(type,id);if(!x)return;const ok=await confirm2({title:'تأكيد الحذف',msg:'سيتم حذف السجل من وحدة إدارة المقاولات.',ok:'حذف',danger:true});if(!ok)return;const map={supplier:'suppliers',rfq:'rfqs',po:'purchaseOrders',subcontractor:'subcontractors',subcontract:'subcontracts',claim:'claims',change:'changeOrders',cash:'cashflow',bank:'bankRecons',due:'dues',user:'users',budget:'budgets'};D()[map[type]]=arr(map[type]).filter(z=>z.id!==id);await svOps(false);auditOps('حذف '+type,x.number||x.name||'');renderOps();renderOpsDashboardStrip();toast('تم الحذف','ok');};

// Re-render strip after load, without adding fake records.
window.addEventListener('load',()=>setTimeout(()=>{try{renderOpsDashboardStrip();}catch(e){}},1200));
})();
